type Location @model @auth(rules: [{ allow: public }]) {
  id: ID! # 一意のID（自動生成）
  name: String! # 店名 / 場所の名前
  description: String # 説明・メモ（自由入力）
  latitude: Float # 緯度（GPS座標）
  longitude: Float # 経度（GPS座標）
  address: String! # 住所
  category: String # カテゴリ（例: ラーメン、カフェ、寿司など）
  priceRange: String # 価格帯
  rating: Float # 評価（例: 1.0〜5.0）
  favorite: Boolean # お気に入り登録フラグ
  hours: String # 営業時間（例: 11:00〜22:00）
  closed: String # 定休日（例: 火曜日）
  imageUrl: String
}

type User
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "cognitoSub" } #
      { allow: public, operations: [read] } # 誰でも読み取りだけできる
    ]
  ) {
  id: ID!
  cognitoSub: String!
  username: String!
  profileImage: String
  email: String! @auth(rules: [{ allow: owner, ownerField: "cognitoSub" }])
}

type Follow
  @model
  @auth(
    rules: [
      { allow: owner } # 自分だけが作成/削除できる
      { allow: public, operations: [read] } # 誰でもフォロー関係を読み取り可
    ]
  ) {
  id: ID!
  followerId: ID! # フォローする側(User.id)
  followeeId: ID! # フォローされる側(User.id)
  createdAt: AWSDateTime
}
