AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Cognito PostConfirmation Lambda

Resources:
  signupLinkToDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x # Node.js バージョンは最新に合わせる
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: User-6no7ty6ug5f2jmfci4crulr7de-NONE # DynamoDB のテーブル名
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
