// src/vocabularies.ts
export const vocabularies = {
  "Sign in": "ログイン",
  "Sign In / Create Account": "ログイン",
  "Create Account": "アカウントの作成",
  Email: "メールアドレス ",
  Password: "パスワード ",
  "Confirm Password": "パスワードの確認",
  "Forgot your password?": "パスワードをお忘れの場合",
  "Reset Password": "パスワードをリセット",
  "Back to Sign In": "ログイン画面に戻る",
  Submit: "登録",
  Confirm: "確認",
  "Sign Out": "ログアウト",
  Username: "メールアドレス ",
  "Send Code": "コードを送信",
  Code: "コード",
  "New Password": "新しいパスワード",
  "Confirm Sign Up": "新規アカウントの確認",
  "Resend Code": "再送する",
  "Lost Code?": "メールが届かない場合",
  Create: "作成",
  "Have an account?": "作成済みの場合は",
  "Sign In Here": "こちら",
};
